package com.indrajha.sasquiz;

public class Part2AnswersList {
    public static String[] answers = {
            "CDA (O) Account Number",
            "Part II orders",
            "double the normal rates prescribed ",
            "cannot prefix or suffix Sunday and holiday ",
            "Are not entitled to advance for purchase of Motor Cars",
            "Leave",
            "PCDA (O)",
            "20 days",
            "Individual Running Ledger Account",
            "Is same as for civilians",
            "Defence Service Officers Provident Fund",
            "within one month from the date of promotion",
            "the following day",
            "on which the orders rescinding the promotion reach the H.Qrs. of unit/formation ",
            "90",
            "cease to draw his pension during period of reemployment ",
            "Regional Controllers",
            "Visual",
            "6 and 1",
            "PLI Cell ",
            "LIC section",
            "2",
            "Technical section",
            "Technical Section",
            "2 years 6 months",
            "Special List Officers",
            "Regimental Commissioned ",
            "Within six months",
            "3",
            "30",
            "11",
            "Central Index",
            "PAO of the Imprest Holder",
            "LPC",
            "Ledger wing",
            "Sick List Concession",
            "25",
            "Ledger wing",
            "30 days",
            "DIDS is raised",
            "None",
            "All the three",
            "30 days",
            "One month",
            "HAFA",
            "Monthly Pay System cell ",
            "It can be accumulated",
            "B.P X (100 /103)",
            "Central Index",
            "Study Leave",
            "Ledger wing",
            "15",
            "Both",
            "Full",
            "Strategic Forces Allowance",
            "Duty",
            "Major General",
            "Quadruplicate",
            "35 years",
            "T Advance Payment Cell",
            "Goods train",
            "Technical Section",
            "Moving Record",
            "None",
            "00/018/61",
            "Either a or b",
            "LPC",
            "Task holder ",
            "None",
            "00/018/65",
            "3",
            "Form ‘A’",
            "Hospital Admission / Discharge",
            "Wing officer (AN)",
            "1",
            "Ledger wing ",
            "Both",
            "Battle casualties",
            "Records",
            "Schedule III",
            "Task Number dealing with his IRLA ",
            "Authorization Slip",
            "Prisoners of war",
            "Records Section ",
            "Ledger wing concerned",
            "Account Number of Army Officer ",
            "DO II Transcription sheets",
            "Nominally",
            "Secondment case",
            "Ledger wing",
            "Two digits Number",
            "Both",
            "Recurring nature",
            "Ledger Wing",
            "Three digits number",
            "AG’s Branch",
            "AMC/ADC",
            "Special tracing",
            "Nil",
            "Six digits number with alphabet",
            "Both",
            "AAOBSO",
            "All the three",
            "one year",
            "Third",
            "Case file of the respective officer ",
            "IAFF 1017 (Outer II)",
            "Field Treasury Chest Receipt",
            "6",
            "12",
            "NCC whole time officers without any former Govt. service",
            "IAFF 1017 (Outer I A)",
            "Payment of pension to widows of deceased army officers",
            "3",
            "12 months",
            "Officer holding higher ranks in a substantive capacity ",
            "PCDA/CDA",
            "Old Records section",
            "Deputation case",
            "‘B’ List Register",
            "One month",
            "Record Section",
            "AAO BSO",
            "No. of IRLAs being maintained in the group",
            "on Supernumerary Strength",
            "Both",
            "3 months",
            "01.01.1976",
            "Correct",
            "IAFF – 1017 (Outer I A)",
            "one class below",
            "All the three",
            "Correct",
            "IAFF – 1017 (Outer I)",
            "10",
            "Both",
            "IAFF – 1017 (Outer II A)",
            "All the three",
            "None",
            "9",
            "6,1",
            "PCDA (P) Allahabad",
            "Rent Cell",
            "a month",
            "Nominal Roll Cell",
            "SS coordination group",
            "Annual Leave",
            "AFCAO, New Delhi",
            "Not Traceable",
            "180",
            "Family Pension will be released",
            "one month in a half year",
            "Full",
            "PCDA (O) Pune",
            "Strategic Force Allowance",
            "30",
            "Category A",
            "2/5th ",
            "None",
            "100",
            "6 months",
            "30 days",
            "PLI Directorate, Kolkata",
            "Red",
            "Correct",
            "6 months",
            "All the three",
            "Special",
            "01.01.1984",
            "4",
            "15",
            "Both",
            "All the three",
            "GOC in C",
            "Height",
            "HAUCA",
            "Sulekha",
            "AG Branch, IHQ of MOD",
            "Technical Section",
            "14 days",
            "Composite Hill Compensatory Allowance",
            "Both",
            "Full at one go",
            "Military Secretary Branch, IHQ MOD",
            "All the three",
            "LW Co-ord (AT)",
            "Army Welfare Housing Organization",
            "Hard Area Allowance",
            "All the three",
            "4",
            "Military Secretary Branch, IHQ MOD",
            "Meghdoot",
            "Both",
            "PAN",
            "Six months",
            "Draft Gazette Notification",
            "7",
            "Input",
            "Moving",
            "Military Secretary Branch, IHQ MOD",
            "Ledger wing",
            "None",
            "PCDA (O)",
            "None",
            "SAO/AO",
            "180 days",
            "Gallantry Awards",
            "95 days",
            "Full Pay Commissioned Service Certificate",
            "10 days",
            "Quadruplicate",
            "Disciplinary Grounds",
            "4 months",
            "Tour of Inspection",
            "CDA (PD) Meerut",
            "Six",
            "Technical Section Group II of PCDA (O)",
            "Imprest Holder ",
            "35 years",
            "a month",
            "All the three",
            "None",
            "Both a, b",
            "All the three",
            "Para pay will not be issued until the result of the enquiry is promulgated ",
            "Time spent on journey to the place of study and return to the place of posting on completion study leave, will reckon as study leave",
            "Study leave",
            "None",
            "Half of the amount",
            "Both a, b  ",
            "Army Officers’ Benevolent fund",
            "Both",
            "During any absence from duty without leave ",
            "10",
            "Authorization Slip",
            "HAUCA",
            "Adjutant General ",
            "Tenure",
            "Sick List Concession",
            "10",
            "Station",
            "Field Cashier Group Sub Section",
            "LW SS Coordination Group (Admin)",
            "Input",
            "365 days",
            "Annual Leave",
            "Monthly",
            "Divisional Commander",
            "LW SS Co-ordination (Admin)",
            "Technical Section, year",
            "6",
            "Annual Leave",
            "5 years",
            "10"
    };

}
