package com.indrajha.sasquiz;

public class Part2OptionsList {
    public static String[] opt = {
            "Individual Account Number","IRLA account number","CDA (O) Account Number","Regiment Account Number",
            "Govt. orders","Part II orders","Audit report","Executive orders",
            "Normal rates prescribed ","double the normal rates prescribed ","Rates of actual expenditure","Rates approved by GOC in C",
            "can prefix or suffix Sunday and holiday","cannot prefix or suffix Sunday and holiday ","can prefix with approval of Controlling officer","can suffix with approval of Controlling officer",
            "Are entitled to advance for purchase of Motor Cars ","Are not entitled to advance for purchase of Motor Cars","Are entitled to advance only if PCDA (O) approves","Are entitled to double the amount prescribed",
            "Administrative Action","Disciplinary action","Leave","Duty assignment",
            "Officers concerned","PCDA (O)","Regional CDA","AO GE",
            "8 days","12 days","15 days","20 days",
            "Individual Running Leave Account ","Individual Running Ledger Account","Integrated Record of Leave Account","Integrated Record of Ledger Account",
            "Is different from civilians","Is same as for civilians","DA is not paid to Army officers","is determined by MOD separately",
            "Defence Service Officers Pension Fund","Defence Service Officers Provident Fund","Defence Service Officers Private Fund","Defence Service Officers Permanent Fund",
            "Soon after the promotion","within one month from the date of promotion","within 2 months from the date of promotion","within one year from the date of promotion",
            "The same day","the following day","date of issue of order","date decided by Controlling Officer",
            "on which the orders rescinding the promotion reach the H.Qrs. of unit/formation ","of issue of order","of grant of erroneous promotion ","of receipt of order by PCDA (O)",
            "100","90","80","75",
            "continue to draw his pension","cease to draw his pension during period of reemployment ","Draw both salary and pension","Exercise choice to draw either",
            "PCDA (O)","Regional Controllers","LAO Supply Depot","Executive Authorities",
            "Reminder","Increment","Visual","Nominal",
            "4 and 3","5 and 2","1 and 6","6 and 1",
            "Rent Cell","Nominal Roll Cell","Pension cell","PLI Cell ",
            "PLI Cell sub section","Field Cashier Sub Section","Pension/Leave Salary Sub Section ","LIC section",
            "2","3","4","5",
            "Ledger wing","Accounts Section","Transportation section","Technical section",
            "Admin Section","LW Coordination Group (Admin)","Accounts Section","Technical Section",
            "4 years 4 months","3 years 3 months","2 years 6 months","2 years 2 months",
            "Sick List Officers","Special Liaison Officers","Special List Officers","Special Level Officers ",
            "Recently Commissioned ","Reserve Commissioned ","Regimental Commissioned ","Regular Commissioned ",
            "Within one year","Within six months","Within three months","There is no limit",
            "2","3","4","None",
            "50","40","30","25",
            "11","12","13","14",
            "Visual Chart","Central Index","Non Effective list ","All the three",
            "M Section of Regional CDA of Imp. Holder ","PAO of the Imprest Holder","Regional CDA of PAO of Imprest Holder","All the three",
            "Part II order","Government sanction","Form ‘A’","LPC",
            "Accounts Section","Administration","Technical Section","Ledger wing",
            "Annual Leave","Furlough","Sick List Concession","Sick Leave",
            "18","21","23","25",
            "Ledger wing","Technical Section","Records Section","Accounts Section",
            "20 days","30 days","60 days","90days",
            "Such amount is noted in a demand register ","Demand Intimated to respective PAO","Acknowledgement watched ","DIDS is raised",
            "Course of instructions to abroad ","Study Leave","Temporary Duty","None",
            "Chief of Army Staff","DGAFMS","Lt. Gen of AFMS","All the three",
            "30 days","15 days","45 days","60 days",
            "One month","Two months","45 days","One year",
            "HAFA","HAUCA","Flying Allowance","None",
            "Administration section","D section","Ledger wing/group","Monthly Pay System cell ",
            "It is two months in every 3 calendar years","When granted in different spells, total should not exceed 60 days in a cycle","It can be accumulated","None",
            "B.P  - 3% of B.P","B.P X (100 /103)","B.P X (103/100)","B.P X (97/100)",
            "Central Index","Visual Chart","Nominal Roll","None",
            "Temporary duty","Course of Instruction","Study Leave","All the three",
            "Technical section","Ledger wing","Accounts Section","Records Section",
            "10","15","30","60",
            "HAUCA","Flying Allowance","Both","None",
            "Full","Half","1/3rd ","2/3rd ",
            "HAFA","CMFAA","CFAA","Strategic Forces Allowance",
            "Duty","Leave","duty/leave depending upon the merits of the case ","Furlough leave",
            "Brigadier","Major General","Lt. General","Colonel",
            "Duplicate","Triplicate","Quadruplicate","Quintuplicate",
            "35 years","75 years","10 years","5 years",
            "T Advance Payment Cell","Single Advance Payment Cell","T Single window cell","Single Window Cell",
            "Goods train","Entitled class of officer","Road Transport ","Not admissible at all",
            "Administration section","Ledger wing","Accounts Section","Technical Section",
            "Temporary record","Frequently asked record","Moving Record","New Record",
            "Technical","Records","Accounts ","None",
            "00/018/60","00/018/61","00/018/64","00/018/65",
            "Temporary rejected transactions ","Completely rejected transactions ","Either a or b","None",
            "Commission order","Part II order regarding reporting to duty","LPC","None",
            "Task holder ","EDP system","Both","None",
            "Legal Cell","RTI Cell","Officers Reception and Information Cell ","None",
            "00/018/64","00/018/65","00/018/60","00/018/61",
            "1","2","3","4",
            "Part II order/DO II","Commission order issued by appointing authority ","Form ‘A’","Sanction of MOD",
            "Hospital Admission / Discharge","Hospital stoppage Rolls","Sick list","All the three",
            "Wing officer (D)","Wing officer (Ledger wings)","Wing officer (EDP)","Wing officer (AN)",
            "2","1","3","4",
            "Account Number of Army Officer ","Task Number dealing with his IRLA ","Ledger wing ","Check Alpha",
            "New Case file is opened ","New CDA (O) Account Number is allotted ","Both","None",
            "Battle casualties","Physical casualties","Both","None",
            "EDP","DO II","Ledger","Records",
            "Cheques","Schedule III","CMP figure","Vouchers",
            "Check Alpha","Account Number of Army Officer ","Task Number dealing with his IRLA ","Ledger wing",
            "Entitlement IRLA","Entitlement slip","Authorization Slip","All the three",
            "Prisoners of war","Pensioners of war","Peace Or War Establishment","All the three",
            "Ledger wings","Accounts section","Permanent Records section","Records Section ",
            "Technical Section","Ledger wing concerned","Accounts Section","All the three",
            "Ledger wing","Account Number of Army Officer ","Task Number","Check Alpha",
            "DO II rejections lists","DO II acceptance lists","DO II Transcription sheets","All the three",
            "Nominally","as usual for all officers","IRLAs are transferred to Embassies ","None",
            "Serving case","Special case","Separate case","Secondment case",
            "Legal Cell","Ledger wing","Permanent Record Section","Technical Section",
            "Alphabets","Single Digit Number","Two digits Number","Three digits number",
            "due to inability of an officer to join or rejoin duty on a/c of Civil commotion ","for pursuing higher Technical and Scientific Studies","Both","None",
            "Recurring nature","Non recurring nature ","Unit allowances claims","Miscellaneous claims",
            "Technical Section","Ledger Wing","Legal Cell","Administration section",
            "Single Digit Number","Two digits Number","Three digits number","Alphabets",
            "E in C Branch","Military Secretary’s Branch","AG’s Branch","QMG’s Branch",
            "AMC/ADC","Colonel and above level","Both","None",
            "Personal tracing","Duplicate tracing","Account tracing","Special tracing",
            "Debit","Nil","Credit","All the three",
            "Two digits number","Six digits number","Six digits number with alphabet","Unit code",
            "Statement of Account","PCDA (O) Website","Both","None",
            "AAOBSO","LAO/RAO","Regional PCDA/CDA","All the three",
            "PLI","Field Cashier","Pension/Leave Salary Contribution ","All the three",
            "6 months","one year","one month","3 months",
            "First","Second","Third","None",
            "Batches/Bundles","IRLA of respective officer","Case file of the respective officer ","retained by EDP",
            "IAFF 1017 (Outer II)","IAFF 1017 (Outer II A)","IAFF 1017 (Outer I)","IAFF 1017 (Outer I A)",
            "Field Treasury Cash Receipt","Field Treasury Consolidated Receipt ","Field Treasury Chest Report ","Field Treasury Chest Receipt",
            "5","6","8","10",
            "10","11","12","15",
            "Commissioned officers of Army ","NCC officers","NCC whole time officers without any former Govt. service","None",
            "IAFF 1017 (Outer I A)","IAFF 1017 (Outer II A)","IAFF 1017 (Outer I)","IAFF 1017 (Outer II)",
            "Maintenance of DSOP accounts of Army Officers","Payment of pension to widows of deceased army officers","Supply of funds to Field Cashiers ","Payment of TA/DA, LTC claims of army officers",
            "2","3","4","5",
            "12 months","24 months","36 months","60 months",
            "Officer holding higher ranks in a substantive capacity ","Holding higher rank in acting capacity","Both","None",
            "Officer by whom it is received/recovered","Next higher officer","GOC in C","PCDA/CDA",
            "Record Section","Permanent Record Section","Old Records section","None",
            "Deputation case","Deserter case","Death case","Dismissal case",
            "‘A’ List Register","‘B’ List Register","‘T out’ List Register","None",
            "One month","2 months","3 months","None",
            "Technical Section","Senior Superintendent Coordination group","Reception & Information cell","Record Section",
            "PCDA (O)","Regional PCDA/CDA","AAO BSO","All the three",
            "No. of IRLAs Transferred out","No. of IRLAs Transferred in","No. of IRLAs being maintained in the group","All the three",
            "on training","on Supernumerary Strength","on Skeleton Strength","on Extra Establishment",
            "Army Officers","DAD staff on Deputation","Both","None",
            "12 months","9 months","6 months","3 months",
            "01.01.1948","01.01.1996","01.01.1986","01.01.1976",
            "Correct","Wrong","Depends on case to case","Decided by CO of the unit",
            "IAFF – 1017 (Outer I)","IAFF – 1017 (Outer I A)","IAFF – 1017 (Outer II)","IAFF – 1017 (Outer II A)",
            "As per ","one class below","two classes below","class decided by PCDA/CDA and not as per",
            "NCC Officers","TA Officers","MNS Officers","All the three",
            "Correct","Wrong","Depends on case to case","Decided by CO of the unit",
            "IAFF – 1017 (Outer I)","IAFF – 1017 (Outer I A)","IAFF – 1017 (Outer II)","IAFF – 1017 (Outer II A)",
            "2","3","8","10",
            "Surplus establishment held by unit is objected in audit ","Posting out of the excess is watched ","Both","None",
            "IAFF – 1017 (Outer I)","IAFF – 1017 (Outer I A)","IAFF – 1017 (Outer II)","IAFF – 1017 (Outer II A)",
            "On transfer within India ","While proceeding on Course of Instructions exceeding 3 months within India ","While proceeding ex-India on duty","All the three",
            "Temporary Advance","Final Withdrawal","Withdrawal for financing LIC policies","None",
            "2","5","9","4",
            "5, 2","4,3","6,1","7,0",
            "PCDA (O) Pune","CDA (PD) Meerut","PCDA (P) Allahabad","All the three",
            "SS Coordination Group","Rent Cell","EDP","Permanent Record section",
            "a year","six months","three months","a month",
            "Permanent Record section","EDP","Nominal Roll Cell","Records section",
            "Record Section","EDP centre","Ledger wing","SS coordination group",
            "Casual leave","Sick leave","study leave","Annual Leave",
            "PCDA (O)","AFCAO, New Delhi","CDA (Funds) Meerut","PCDA (AF) Dehradun",
            "Not Traceable","Special Tracing – No such account found ","Account does not exist","Any of the three",
            "180","240","200","150",
            "Pay will be continued","HAUCA if in issue will be discontinued","Family Pension will be released","None",
            "One month in a quarter","one month in a half year","two months in a half year","None",
            "Full","10 Instalments","@ 1/3rd of pay","Instalments decided by PCDA",
            "PCDA (O) Pune","PCDA (Navy) Mumbai","PCDA (AF) Dehrudun","All the three ",
            "Strategic Force Allowance","Siachen Allowance","Both","None",
            "10","20","30","60",
            "Category A","Category B","Both","None",
            "1/3rd ","1/4th ","2/3rd ","2/5th ",
            "To ensure that an officer is paid only one section at a time","To ascertain ledger wing dealing with particular IRLA ","To ascertain the Effective status of Account ","None",
            "100","66.66","50","33.33",
            "3 months","6 months","one year","two years",
            "180 days","90days","60 days","30 days",
            "PLI Directorate, New Delhi","PLI Directorate, Kolkata","Both","None",
            "Red","Green","Black","Any of the three",
            "Correct","Wrong","Decided by CO of the unit","Decided by PCDA (O)",
            "24 months","12 months","6 months","3 months",
            "Military Farms","Military Engineering units","Training Centres","All the three",
            "Separate","Special","Secret","Specific",
            "01.01.1976","01.01.1984","01.01.96","01.10.97",
            "2","3","4","5",
            "14","15","18","20",
            "Officers posted to Embassies abroad","Officers on Deputation","Both","None",
            "Officiating Command Allowance ","Reimbursement of Medical charges (OPD) ","Terminal Gratuity","All the three",
            "Sub Area Commander","Area Commander","GOC in C","All the three",
            "Area","Height","Depth","Operational risk",
            "HAFA","CFAA","CMFAA","HAUCA",
            "Suvigya","Sulekha","Sugam","Skylark",
            "AG Branch, IHQ of MOD","Ledger Wing of PCDA (O)","Accounts Section of PCDA (O)","Military Secretary Branch",
            "Transportation wing","Administration section","SS coordination (Audit)","Technical Section",
            "6 weeks","one month","21 days","14 days",
            "Composite Hill Counter Insurgency Area","Composite Hill Compensatory Allowance","Composite Hard Climate Area Allowance","Compensatory Hard Climate Area Allowance",
            "Temporary/Final withdrawal from DSOP fund ","Loans and Advances","Both","None",
            "Full at one go","In three equal installments","In two equal installments ","Installments decided by PCDA (O)",
            "Military Secretary Branch, IHQ MOD","AG Branch IHQ MOD","GOC in C","GOI",
            "Encashment of Annual Leave","Credit Balance of IRLA","Terminal Gratuity Claim","All the three",
            "LW Co-ord (AT)","Records Section","Accounts Section","Administration Section",
            "Army Welfare Health Organization","Army Welfare Housing Organization","Army Women officers Health Organization","Army Women Health Officer",
            "HAFA","Hard Area Allowance","Hill compensatory Allowance","CFAA",
            "Retirement","Pre mature Retirement","Death","All the three",
            "4","3","2","1",
            "Military Secretary Branch, IHQ MOD","AG Branch IHQ MOD","GOC in C","All the three",
            "Vijay","Meghdoot","Blue Star","None",
            "Para Reserve Allowance","Special Commando Allowance","Both","None",
            "PAN","Home Town","e-mail id","All the three",
            "one month","3 months","Six months","One year",
            "Director General Naval Establishment ","Draft Gazette Notification","Draft General Notification ","Draft Government Notification ",
            "4","5","6","7",
            "Input","Authorization slip","Transcription sheet","None",
            "Temporary","Moving","Dynamic","Frequently Required Record",
            "Military Secretary Branch, IHQ MOD","AG Branch IHQ MOD","GOC in C","GOI",
            "Administration Section","Technical Section","Ledger wing","Accounts Section",
            "Short Service Commissioned ","Reemployed","Reserve Officers when recalled","None",
            "AG Branch IHQ MOD","Military Secretary Branch IHQ MOD","PCDA (O)","PCDA (P) Allahabad",
            "Clearance of TA/DA Advances drawn by Army Officers from Imprest holders","Adjustment of MROs","Issue of No Demand Certificates in NE cases","None",
            "Wing Officer","SAO/AO","AAO","Any of the three",
            "30 days","60 days","120 days","180 days",
            "Details of Dependents ","Gallantry Awards","Home Town","None",
            "30 days","60 days","65 days","95 days",
            "Final Pay of Commissioned Service Certificate ","First Pay of Commissioned Service Certificate ","Final Settlement Pay of Commissioned Certificate","Full Pay Commissioned Service Certificate",
            "5 days","10 days","30 days","90 days",
            "Duplicate","Triplicate","Quadruplicate","Quintuplicate",
            "Course of instruction","Disciplinary Grounds","Bonafide Government Duty","All the three",
            "8 months","6 months","4 months","3 months",
            "Tour of Inspection","discharge of duties","Both","None",
            "PCDA (P) Allahabad","Officer Concerned","Ledger wing","CDA (PD) Meerut",
            "Two","Four","Five","Six",
            "Pension cell of PCDA (O)","Ledger Wing of PCDA (O)","Technical Section Group II of PCDA (O)","EDP Centre of PCDA (O)",
            "Imprest Holder ","PCDA (O)","Either a or b","None",
            "75 years","50 years","40 years","35 years",
            "a year","a half year","a quarter","a month",
            "While on duty Ex-India ","While supernumerary to the establishment to his corps ","When he is declared as Prisoner of War","All the three",
            "To supply funds to Field Cashier ","To conduct post audit of Railway Warrants in respect of army officers ","To maintain pay accounts of civilian gazetted officers posted to operational areas  ","None",
            "Any qualification acquired before commissioned in consideration of which a concession in the form of antedate seniority is given","Any qualification which was minimum  required for entry","None","Both a, b",
            "M section","IA section","O & M Section","All the three",
            "Para pay will be admissible to the temporary incumbent ","Para Pay will be admissible to the permanent incumbent ","Para pay will not be issued until the result of the enquiry is promulgated ","Para pay is payable to both the officers.",
            "Time spent on journey to the place of study and return to the place of posting on completion study leave, will reckon as study leave","Study allowance will be admissible during the period of journey","Both a, b correct","None",
            "Furlough","Study leave","Sick Leave","None",
            "Graded Specialist","Classified Specialist","Consultant","None",
            "Half of the amount","full amount","1/3 of the amount","1/4 of the amount",
            "If the move is undertaken in pursuance of tour of inspection","An officer attached to unit at another station on disciplinary grounds ","Both a, b  ","None",
            "Army Officers’ Benefit fund","Army Officers’ Benevolent fund","Army Officers Balancing fund","None",
            "Advance of Pay is not admissible in Mutual Transfer cases ","Advance of pay can be drawn at the new station when transferred","Both","None",
            "On the day of death ","During any absence from duty without leave ","From the next day of transfer to Reserve ","All the above",
            "2","3","5","10",
            "Transcription sheet","Input","Authorization Slip","DO II",
            "Entire Pay and Allowances","Para Allowance","Specialist Allowance","HAUCA",
            "Military Secretary ","Adjutant General ","QMG ","Deputy Chief",
            "Merit","Fixed","Tenure","Special",
            "Non Qualifying Service","Absence without leave","Sick Leave","Sick List Concession",
            "10","12.5","25","No fixed percentage",
            "Task","Station","corps ","None",
            "Field Cashier Group Sub Section","Disbursement Section","Ledger wing","Technical Section",
            "Accounts Section","LW SS Coordination Group (Org & Audit)  ","Technical Section ","LW SS Coordination Group (Admin)",
            "Authorization Slip","Input","DO II Transcription Sheet","All the three",
            "6 months continuous service","365 days","Both","None",
            "Furlough leave","Annual Leave","As applied by Officer","Discretion of Competent Authority",
            "Daily","weekly","Monthly","Yearly",
            "Divisional Commander","GOC in C","Army H.Qrs.","CGDA",
            "LW SS Co-ordination (Admin)","Technical Section","Records Section","LW SS Co-ordination (Org & Audit)",
            "Administration Section, half year ","Administration section, year","Technical Section, half year","Technical Section, year",
            "10","9","8","6",
            "Annual Leave","Furlough","Absence without pay","Special Casual Leave",
            "10 years","5 years","3 years","1 year",
            "2","3","5","10"
    };
    ////end of options
}
