package com.indrajha.sasquiz;

public class Part1AnswersList {
    public static String[] answers = {
            "GS",
            "Armoured",
            "Vice Chief",
            "Deputy Chief",
            "Visakhapatnam",
            "Two Tier",
            "Reviewing, Accepting",
            "None",
            "PC of A Kolkata",
            "None",
            "60",
            "One-Half",
            "Buy and Sell",
            "Parliament",
            "C&AG",
            "Outcome",
            "One to One",
            "Statement of Budget Estimate",
            "IAS officer",
            "Supreme Court Judge",
            "C&AG",
            "Both",
            "FADS",
            "Not operative",
            "Probationer",
            "LAO",
            "Only 3",
            "January",
            "Judge of a High Court",
            "2",
            "Treasury",
            "6 months",
            "None",
            "None",
            "5",
            "Hindi",
            "None",
            "None",
            "CIC",
            "Family member",
            "Drawing Officer",
            "Medium-term Expenditure Framework Statement",
            "Both",
            "7",
            "Can be permitted to get enrolled but should not engage in legal profession as long as in service",
            "Both",
            "61",
            "Speaker of the House of People",
            "Attorney General",
            "Prime Minister",
            "12",
            "151",
            "0.1",
            "Minor",
            "3",
            "Highest authority with consent of others may order for common proceeding",
            "All the three",
            "Refer the matter with facts to superior and take action as per decision of superior",
            "Action of X is correct and Y is not correct",
            "Speculation",
            "High Court",
            "All the three",
            "Artillery Centre, Nashik",
            "Dept. of Defence",
            "PCDA Bengaluru",
            "GREF Pune",
            "Bengaluru",
            "Performance",
            "Budget",
            "All the three",
            "Departmentally Related Standing Committee",
            "Outcome",
            "Both",
            "11",
            "8",
            "None",
            "Proforma Controller",
            "None",
            "Both",
            "Office",
            "District Officer",
            "7",
            "President",
            "Chairman of CAT",
            "None",
            "station where there is lack of normal amenities of life",
            "None",
            "A or B",
            "After 200 pages, fresh volume of the file is opened?",
            "a or b",
            "180",
            "Social Welfare Officer",
            "All the three",
            "Cabinet",
            "MS branch",
            "Defence Minister’s Appellate committee",
            "Vehicle Factory Jabalpur",
            "7",
            "The Production wing of Dept. of Defence Production and Supplies",
            "Shillong",
            "Transparency",
            "Consolidated Fund of India",
            "Article 323A of the Constitution",
            "Both A and B",
            "Form No. ATC-4.",
            "the  number  of  such workers  is  less  than ten",
            "The President",
            "Chief of Logistics",
            "Bangalore",
            "90 days",
            "None of these",
            "every five years",
            "Either A or B, whichever is less/earlier",
            "Form – IAFA 487",
            "None of these",
            "Financial Commissioner of Railways",
            "Not exceeding three years from the date of nomination",
            "Supreme Court Judge",
            "C&AG",
            "All of these",
            "PCDA/CDA",
            "No, there is no limit",
            "Both A and B",
            "Expenditure       on instructional films/film strips",
            "3 months from the date of incident",
            "Chandigarh",
            "All of these",
            "‘Minus debits’.",
            "Air Fore",
            "All of these",
            "The  Chief  Justice  of India",
            "Public Financial Management System",
            "The     President     of India",
            "Central Govt, Both the houses of parliament",
            "60",
            "One-Half",
            "Buy and Sell",
            "Parliament",
            "Outcome",
            "Qualified exemptions",
            "No",
            "Fine      up      to      Rs 50,000/-     for     first instance",
            "Either A or B",
            "The Central Government",
            "9th   December 2013",
            "Engineer-in-Chief",
            "All of these",
            "The CGA",
            "At   the   first   session meeting      immediate after   the   advance   is sanctioned",
            "Section 10",
            "as a period spent on duty",
            "Department            of Administrative Reforms  and  Public Grievances",
            "30 days",
            "Pioneer Corps",
            "The accused in cross cases will be tried separately and both trials should       be      held simultaneously.",
            "Jai      Shree      Varte Veeram",
            "Air Commodore",
            "Department of Defence",
            "2004",
            "Service Money orders",
            "40% of the Fund",
            "Efficiency-Cum- Performance Audit",
            "Major General",
            "Defence Security Corps",
            "Disciplinary Authority",
            "Joint Secretary level officer",
            "None of these",
            "40 days",
            "Held in material form",
            "All the above",
            "Three",
            "Need not be reported to the Government as they do not come within the purview of Conduct Rules",
            "UMANG",
            "Accounts Officer",
            "Presenting Officer",
            "Without               any receivable order",
            "The  final  decision  is taken",
            "PCDA/CDA",
            "Claimant",
            "Under orders of a court of competent jurisdiction",
            "related    to     service delivery.",
            "Expenditure Heads",
            "Not necessary",
            "Fixtures      do      not comprise stores",
            "Inquiry Officer",
            "General Staff",
            "Service HQs",
            "GoI",
            "11",
            "Disciplinary Authority",
            "Hindi or English",
            "31st January",
            "E in C",
            "The Prime Minister",
            "Previous sanction must",
            "90 days",
            "District Officer",
            "Commanders-in- Chief",
            "33",
            "In           case           of international     travel only",
            "Public account of India",
            "Dept   of   Economic affairs",
            "Annual budget circular",
            "3",
            "Budget           estimates, Revised  estimates  and Actuals",
            "President of India",
            "1st February",
            "statement I",
            "demands for grants",
            "statemnet II",
            "detailed  demands  for grants",
            "economic survey",
            "departmentally related standing committees",
            "Fixtures        do        not comprise stores",
            "Adjustment          made among      owners      of vessels and of cargo",
            "3",
            "locally           controlled heads",
            "economy cut",
            "token cut",
            "centrally       controlled heads",
            "No",
            "No write off is required",
            "Short                 Term Agreement",
            "Reduction in rates",
            "12 months",
            "Charged expenditure",
            "From one primary unit of    appropriation    to another such unit",
            "177",
            "Pioneer Corps",
            "Defence Minister’s (Production and Supply) Committee",
            "Army H.Qrs.",
            "None",
            "Reference  to  the  No. & date of letter",
            "5 years",
            "General Staff",
            "23768",
            "A",
            "Both",
            "Transportation section",
            "Disbursement",
            "1 year",
            "0.8",
            "Part II",
            "Admiral",
            "30",
            "PCDA/CDA",
            "Pink/Civil",
            "30th June",
            "Army Service Corps",
            "a policy cut",
            "Adjutant General",
            "Corps of Engineers",
            "MS branch",
            "Defence Minister’s Appellate committee",
            "Vehicle Factory Jabalpur",
            "7",
            "The Production wing of Dept. of Defence Production and Supplies",
            "Corps",
            "Flag Officer commanding in chief",
            "4",
            "Southern Air Command",
            "Shillong",
            "Vice Chief of Army Staff",
            "Ministry of Defence",
            "Chief of Army Staff",
            "Defence Research and Development Council",
            "Station Transport Offices",
            "Flying Officer",
            "Trivendrum",
            "All the three",
            "Finance Division",
            "Quarter Master General",
            "Air Commodore",
            "FOC in C Southern Naval Area, Kochi",
            "Pioneer Corps",
            "All the three",
            "Department of Defence Finance",
            "Member having been the longest in the committee",
            "MOD",
            "MOD",
            "Principal Staff Officers",
            "Production wing of Department of Defence Production and Supplies",
            "2",
            "7",
            "Defence Minister’s (Production and Supply) Committee",
            "Directorate of Planning and Coordination",
            "Defence Research & Development Council",
            "Dept. of Defence R & D",
            "Chief of Army Staff",
            "DRDO, New Delhi",
            "GS Branch",
            "AG Branch",
            "MGO Branch",
            "Military Secretary Branch",
            "Engineer in Chief Branch",
            "Defence Security Corps",
            "Sub Area",
            "Mobile",
            "Army Service Corps",
            "5",
            "5",
            "Lieutenant",
            "Vice Admiral",
            "Captain",
            "Commodore",
            "Rear Admiral",
            "Admiral",
            "Battalion",
            "10",
            "ASC",
            "Principal Staff Officers",
            "E in C",
            "Lt. Colonel",
            "Chief of Integrated Defence Staff",
            "Major General",
            "Major",
            "Station HQrs",
            "Corps of Engineers",
            "Both",
            "MGO Branch",
            "Quarter Master General",
            "General Staff",
            "Adjutant General",
            "Master General of Ordnance",
            "Captain",
            "Army Service Corps",
            "Artillery",
            "Both",
            "Adjutant General",
            "None",
            "Production",
            "EME",
            "AG Branch",
            "Corps of EME",
            "Navy",
            "University Entry Scheme",
            "Defence",
            "Army H.Qrs.",
            "None",
            "Subdedar",
            "Army Education Corps",
            "MOD",
            "New Delhi",
            "Remount and Veterinary Corps",
            "Army Medical Corps",
            "Corps of Military Police",
            "Military Nursing Service",
            "3",
            "Viskhapatnam",
            "Chief of Logistics",
            "FOC in C Visakhapatnam",
            "28157",
            "11",
            "DG of Indian Coast Guard",
            "Squadron Leader",
            "Flying Officer",
            "Lieutenant",
            "Port blair",
            "Air Vice Marshal",
            "Engineer India Ltd. (EIL)",
            "E in C",
            "Quarter Master General",
            "General Staff",
            "E in C",
            "Adjutant General",
            "Major",
            "Army Service Corps",
            "Artillery",
            "Chief of Logistics",
            "Deputy Chief of Air Staff",
            "Dept. of Defence Production",
            "Dept. of Defence Research & Development",
            "Dept. of Ex Servicemen welfare",
            "MGO branch",
            "A",
            "30",
            "Tamil Nadu",
            "343",
            "B",
            "20000",
            "Hindi or English",
            "12 months",
            "351",
            "39947",
            "7",
            "Inquiry Officer",
            "one month",
            "Speculating    in    stock market",
            "31st December",
            "Life Insurance policy (Premium            p.a. exceeding            two months’ basic pay)",
            "Addl. CDA/Jt. CDA",
            "Both",
            "When   the   presenting officer          is          legal practitioner",
            "5 years",
            "6 months",
            "Good",
            "30th June",
            "10",
            "16",
            "Week",

            "Bill",
            "Voucher",
            "2",
            "Pay and Allowances",
            "Gazetted Officer",
            "1983",
            "5",
            "6",
            "8",
            "12",
            "9",
            "8",
            "14",
            "8",
            "All the three",
            "CGA",
            "CGA",
            "CGA",
            "Claim",
            "Compilation sheet",
            "2",
            "01.04.1990",
            "All the three",
            "Take it as  receipt and write off the loss under appropriate head",
            "Cost Accountant",
            "None",
            "None",
            "Both",
            "Both",
            "General Manager",
            "None",
            "1",
            "1",
            "PCDA (P) Allahabad",
            "Preceding year",
            "2",
            "Commutation of Pension",
            "5-6 months",
            "Lt. Colonel",
            "Havaldar",
            "UDC",
            "Gross Pension",
            "2.5",
            "DPDOs",
            "01.01.1978",
            "Internal Audit",
            "Cantonment Boards",
            "PCDA/CDA",
            "Defence Audit Code",
            "DGADS",
            "CGDA",
            "5",
            "None",
            "Accepted Tender Note",
            "1st August",
            "AO/AAO GE/BSO",
            "10th",
            "15th January",
            "Both",
            "Voucher to IRLA and not vice versa",
            "Previous charges",
            "Supplementary pay bill",
            "Executive",
            "None",
            "Central Record Office (Officers) Delhi",
            "Government of India",
            "DAD",
            "Both Initially and finally",
            "Embarkation Commandant",
            "Milrail",
            "Receipts Audit",
            "To prescribe rules and orders",
            "Receipts",
            "CGDA",
            "Voucher to Pay Bill not vice versa",
            "1st July",
            "Both",
            "None",
            "PCDA (CC) Lucknow",
            "QMG",
            "Originating Financial Advice",
            "Demand cum Audit Register",
            "Government of India",
            "2",
            "Director General of Aeronautical Quality Assurance",
            "Pay Bill to Voucher not vice versa",
            "Action is in order",
            "PCDA (O) Pune",
            "Scale Audit",
            "countersigned by CFA",
            "a or b",
            "16th of the month",
            "PCDA New Delhi",
            "Higher authority through PCDA/CDA",
            "PCDA (O)",
            "Contracts concluded by MES",
            "2",
            "Both",
            "Government of India",
            "GOC in C by Name",
            "6 weeks",
            "Both",
            "Quarterly",
            "30 days",
            "Income Tax Register",
            "Half yearly",
            "Double",
            "Another Auditor",
            "CGDA",
            "PCDA/CDA",
            "Cancelled",
            "FADS/Secretary (Def/Fin)",
            "Public Accounts Committee",
            "3",
            "None",
            "Secretary (Def/Fin)/FADS",
            "2",
            "1st September",
            "RAO/LAO",
            "Secretary (Def/Fin)/FADS",
            "Annual Audit Certificate",
            "Fresh Irregularities",
            "None",
            "3",
            "Cash",
            "Cash",
            "Cantonment Boards",
            "Stores",
            "a or b",
            "Concerned Administrative Authority",
            "Audit of Government of India Sanctions",
            "PAOs (ORs)",
            "PCDA New Delhi",
            "Naval Pay Office",
            "C&AG",
            "Sanction",
            "Internal Audit",
            "All the three",
            "Require pre scrutiny by CDA",
            "None",
            "Military Engineering services",
            "Government of India",
            "Lowest of two",
            "June, Sept, December, March",
            "None",
            "DGADS",
            "Receipt to Government",
            "None",
            "20th",
            "Transaction audit",
            "Daily",
            "Cash irregularities reported already",
            "Unavoidable losses",
            "Authority administering the appropriation",
            "Cashing of private cheques",
            "Stores irregularities reported fresh",
            "DFA (works)",
            "Standards of Financial Propriety",
            "Both",
            "DIDS is raised",
            "Annual Review of Balances under heads of Accts.",
            "Cantonment Funds",
            "None",
            "Returned to PCDA/CDA",
            "Iron & Steel Controller, Kolkata",
            "DAD",
            "PCDA/CDA",
            "From IRLA to Documents not vice versa",
            "SAO/AO",
            "To prescribe rules",
            "PCDA New Delhi",
            "Should be in personal terms",
            "CFA",
            "CFA",
            "Yes. At his/her discretion",
            "PCDA/CDA",
            "From Documents to IRLAs not vice versa",
            "Financial Advice",
            "Freight collect basis",
            "Sanction Audit",
            "3",
            "Concerned Administrative Authority",
            "Controller who raises the issue",
            "T section",
            "Impersonal",
            "Licence Fee bills",
            "Gross",
            "2",
            "5",
            "debit",
            "Cash balance",
            "Warrants for money",
            "Ceiling Monetary limit",
            "Scales of Rations and Supplies",
            "DGADS",
            "Divisional or Formation Commander",
            "C&AG of India",
            "AOGE",
            "31st March & 30th September",
            "Surplus",
            "Conveyance Charges",
            "Demand Intimations",
            "PCDA (O)",
            "a or b",
            "Nearest Regional CDA",
            "Office Contingencies",
            "3 months",
            "Joint Receipt Inspection",
            "In the Draft Para itself",
            "None",
            "Audit Reports",
            "To apply the rules and orders",
            "Respective PAO (ORs)",
            "Six months",
            "Issuing Authority",
            "Executive",
            "March",
            "Power of Attorney is verified with duplicate of GPA",
            "Major Audit – Minor Audit",
            "MFAI report is rendered in two parts with each having two sections A,B",
            "Draft para can be concurred by any IDAS officer in CDA office",
            "Accounting Control",
            "It does not contain cases of irregularities detected in Internal Audit",
            "Naval Armament Supply Officer",
            "PCDA (P) Allahabad",
            "Self Accounting Units",
            "Voucher to IRLA but not vice versa",
            "3",
            "Date of issue of clarification by CGDA",
            "Making independent inquiry in a unit with PBORs",
            "Complementary Pension",
            "PCDA  CC Lucknow",
            "Civilians working in Peace Stations",
            "Commitment by the third party that they will refund in case required",
            "Embarkation Commandant",
            "PCDA (Navy) Mumbai",
            "Sanction Audit",
            "Quarterly",
            "b but not a",
            "authority",
            "MOD",
            "All the three",
            "Military Treasury Remittance",
            "Regional PCDA/CDA",
            "Army H.Qrs.",
            "Yes",
            "Deputy Financial Advisor",
            "Pay & All. Of Civilian Employees",
            "Station",
            "Audit cards",
            "Embarkation Commandant",
            "PCDA/CDA",
            "Locally Controlled heads",
            "LF Bill to Pay Bill",
            "Decided by PCDA/CDA",
            "Original, Responding",
            "Sanction, Expenditure Audit",
            "Scale Audit",
            "Date of receipt of original bill",
            "Completely false",
            "Provisional payments",
            "2",
            "CDA",
            "Pay and Allowances",
            "Pension",
            "Certified Receipt Voucher",
            "Scrutiny of Disciplinary action",
            "CGDA",
            "Both",
            "Formation Commander",
            "15",
            "Cash loss",
            "Aircraft On Ground",
            "Personnel Occurrence Reports",
            "CDA (AF) New Delhi",
            "a firm of professional auditors",
            "Base Supply Officers",
            "Naval H.Qrs.",
            "Monthly",
            "To Present audited accounts of expenditure from appropriations of the year",
            "be formally",
            "CGDA",
            "Both are correct",
            "CDA, Chennai made a provisional payment based on the undertaking by an individual transferred to his office stating that he will refund the amount if required",
            "both",
            "Civil Account Code",
            "CGDA",
            "One Alphabet",
            "All the three",
            "1952",
            "Other Receipts",
            "CGDA, CGDA",
            "Loan head",
            "266",
            "28034",
            "Reduction in Expenditure",
            "Both",
            "267",
            "Sub heads",
            "Military Engineer Service",
            "Borrowing Department",
            "Civil Department",
            "Both",
            "Debt Heads",
            "Suspense Head",
            "Both",
            "3",
            "Defence Services Estimates",
            "5 crores",
            "RBI, CAS",
            "CGA",
            "22737",
            "None",
            "Previous years",
            "Government Accounts Department",
            "266",
            "Turn Around Time",
            "None",
            "4",
            "CGDA",
            "Cash",
            "Reappropriatio n",
            "Charged expenditure",
            "F",
            "Sub Heads",
            "Major head",
            "DAD",
            "Revenue heads",
            "Sub Minor head",
            "Indian",
            "Both",
            "Army",
            "Capital",
            "MOD (Finance)",
            "each year",
            "All the three",
            "Date wise Monthly Statement",
            "90",
            "Issuing a cheque to MHA",
            "00/018/60",
            "7",
            "None",
            "6 months",
            "Service rendered by Army to AF",
            "Sectional Compilation",
            "In cash (cheque) or by demand drafts",
            "2",
            "Heads that appear in CHB",
            "Cash Accounts",
            "Punching Medium",
            "2",
            "None",
            "PCDA (P) Allahabad",
            "Regional PCsDA",
            "Construction of Building",
            "Estimated gross expenditure included in Demands for Grants",
            "67",
            "None",
            "Earnest Money Deposits",
            "Public Fund",
            "six months",
            "IAF CDA 338 - A",
            "Both are equally responsible",
            "8000",
            "15",
            "Reduction of Expenditure",
            "None",
            "Deposit",
            "Addl. CDA/Jt. CDA",
            "Accredited Bank",
            "Detailed & Object",
            "Ways and Means Advances",
            "All the three",
            "TA/DA of MES Industrial Employees",
            "None",
            "CDA Army Meerut",
            "Balances",
            "Government",
            "None",
            "day when SBI receives file from Accounts Office",
            "DIDS",
            "Government",
            "Ministry of Road Transport and Highways",
            "Both",
            "Revolving",
            "CDA",
            "Section",
            "7",
            "Voucher Number",
            "Month",
            "Year",
            "(+) Charge",
            "(-) Charge",
            "(+) Receipt",
            "(-) Receipt",
            "March Supplementary Correction",
            "Capital",
            "RBI",
            "8",
            "Provisional Payment",
            "Ministry of Finance to MOD (Civil)",
            "Fictitious heads",
            "Pension payments",
            "Deduct Entry {(-) Debit/Credit}",
            "AO (DAD) MOD",
            "1 crore",
            "Memo of clearance",
            "PCDA New Delhi",
            "Statement of Central Transactions",
            "None",
            "March Residual",
            "All the three",
            "Secretary, Ministry of Finance (Dept. of Economic Affairs)",
            "Receipts",
            "Audit",
            "LAOs/RAOs",
            "Explanatory",
            "Sectors I to M",
            "Pass it on to correct CDA through DEA",
            "8",
            "Both a & b",
            "Supplementary",
            "Cash Vouchers",
            "Transfer Entries",
            "Civil ID Schedules",
            "Abstract of Receipts & Charges",
            "Cash Accounts",
            "Railway Bills",
            "DID Schedules",
            "MES Bills",
            "Department of Economic Affairs",
            "All the three",
            "Government electronic payment Gateway",
            "CGDA",
            "Both",
            "40177",
            "RBI Act, 1934",
            "Public Account of India",
            "C&AG",
            "cost accounting",
            "15th April",
            "Settlement Account",
            "Capital Expenditure",
            "That plans transfer",
            "Revenue",
            "Triplicate",
            "cash or Demand Drafts",
            "3",
            "department to which he is transferred",
            "Audit",
            "PCDA New Delhi",
            "PCDA (R&D) New Delhi",
            "Major",
            "distributed between the different Governments as mutually agreed upon",
            "3 months",
            "three months",
            "Minor",
            "Both",
            "reduction of Receipts",
            "Defence Proforma Account",
            "Schedule III",
            "Itemized",
            "Suspense",
            "34243",
            "PC of A Kolkata",
            "CGA",
            "Defence Services Estimates",
            "Debit",
            "cash",
            "Financial year",
            "Navy",
            "Loss",
            "Credit",
            "6",
            "Free",
            "PCDA New Delhi",
            "General Managers",
            "None",
            "Advance of Pay",
            "PCDA (P) Allahabad",
            "Directors of Labs/Estts.",
            "All the three",
            "Loans",
            "Quintuplicate",
            "IAF CDA 13",
            "Vote on Account",
            "Modified Appropriation",
            "letter of credit",
            "First",
            "Audit Section",
            "None",
            "Deposit",
            "Annually",
            "the authorities to whom allotments are made",
            "Pay & Allowances head",
            "112 (3) (f)",
            "Part B",
            "a or b",
            "Other than Cash",
            "Returned to the originating CDA",
            "Re appropriation",
            "Defence Exchange Account",
            "Both",
            "Addl. CDA/Jt. CDA",
            "4",
            "IFAs (Command)",
            "Any of the two a or b",
            "Consolidated fund of India",
            "Both",
            "1",
            "Government of India",
            "Lapsed",
            "1",
            "30 years",
            "It does not require submission for vote by parliament",
            "EDP centre of CGDA",
            "7",
            "CGA",
            "Till last day of the month",
            "RBI",
            "Defence Account which has been created proforma in the books of RBI",
            "Defence Exchange Account",
            "Defence Pensions",
            "Defence Secretary",
            "Charged Expenditure",
            "Capital Expenditure of Defence",
            "Book adjustment through RBI, CAS Nagpur",
            "MOD",
            "10, 7",
            "oo",
            "Passed by Parliament",
            "Capital expenditure",
            "One primary unit of appropriation to another such unit",
            "Paid Cheques",
            "Accounts Section",
            "House Building Advance",
            "00/020/61",
            "Demands for Grants",
            "Supplementary Grant",
            "Principal Staff Officers (Service H.Qrs)",
            "Pamphlet of RDR heads",
            "Schedule III",
            "26024",
            "Advance of Pay",
            "25th April",
            "OMROs",
            "93",
            "monthly",
            "Home Ministry",
            "1",
            "Expenditure heads",
            "IFA HQ (SC) Pune",
            "DAD officers",
            "00/020/96",
            "Minor heads",
            "CGDA",
            "Transactions",
            "Sub Function",
            "Programme",
            "Scheme",
            "Sub Scheme",
            "2",
            "3",
            "Primary unit of appropriation",
            "2",
            "Sector",
            "2",
            "Sub Major",
            "Consolidated Fund of India",
            "Contingency Fund of India",
            "PCDA (O) Pune",
            "2",
            "Sectional Compilations",
            "Defence Exchange Account",
            "Appropriation",
            "CGDA",
            "Commercial",
            "(+) Charge",
            "(-) Charge",
            "CDA Patna",
            "Defence Treasury",
            "Revenue Receipts",
            "Ways and Means",
            "March Residual",
            "Resource Operations",
            "Quarter",
            "PCDA/CDA",
            "Charged Expenditure",
            "Loans and Advances",
            "Quasi commercial",
            "Punching Medium",
            "Electronic Clearing Service",
            "National Electronic Fund Transfer",
            "Cash Management Product",
            "Central Online Real time Exchange",
            "Annual Review of Balances",
            "Expenditure on New Services",
            "Real Time Gross Settlement",
            "Both",
            "Daily",
            "Accounts",
            "8",
            "Payment of bill",
            "Suspense",
            "Appropriation",
            "MOD (Civil)",
            "Charged expenditure",
            "Charged",
            "CGDA",
            "Single Entry with Double Entry Principles as required",
            "74",
            "Defence Pensions",
            "Minor Head",
            "Both",
            "Ordinary Revenues",
            "Scheme/Activit y",
            "Sectors I to M",
            "Bank",
            "17",
            "CMP",
            "2",
            "QMG branch",
            "Schedule III",
            "Receipts",
            "Schedule of Demands",
            "Appropriation Act",
            "Focal Point Branch",
            "Government Business Software Solution",
            "Mumbai",
            "4",
            "Cash",
            "Audit",
            "CDA (Army) Meerut",
            "Distributed Data Processing",
            "2",
            "Deputy C&AG of India",
            "31st March",
            "GE",
            "LAO",
            "PCDA/CDA",
            "5",
            "VDMS",
            "will be adjusted by debit to security deposit head & credit to DEA of concerned CDA",
            "Estimates",
            "Estimates Committee",
            "22 (15, 7)",
            "C&AG",
            "None",
            "None",
            "C&AG",
            "1423",
            "Treasury Bills",
            "Consolidated Fund of India",
            "Single Entry System using Double Entry Principles wherever required",
            "Public Accounts Committee",
            "President",
            "Supreme Court Judge",
            "All the three",
            "Charged on to the",
            "Finance Commission",
            "Economy",
            "Efficiency",
            "Effectiveness",
            "22 MPs (15-Lok Sabha, 7- Rajya Sabha)",
            "30 MPs (30-Lok Sabha, 0- Rajya Sabha)",
            "Cash",
            "Both",
            "Central Audit/Local Audit",
            "1976",
            "Pay Accounts Office",
            "Defence Treasury",
            "District Treasury Officers",
            "Deputy C&AG",
            "President",
            "Concurrence of Financial Adviser",
            "500",
            "At the request of Senior Audit officer of command, in which case sent to him personally",
            "Both",
            "debt owed to public",
            "Miscellaneous Expenditure",
            "None",
            "GOI",
            "48",
            "Three years excluding year of deposit",
            "None",
            "Both",
            "One year",
            "At the first instance only technical bid is opened",
            "10000",
            "Executive Authorities",
            "Transfer of funds from one budget head to another",
            "LAO/CDA/PCDA",
            "3 years",
            "GOC in C of NC & EC",
            "Rs. 25,000",
            "DPM",
            "Date of issue",
            "Similar articles",
            "Finance Ministry",
            "All",
            "Both",
            "Net",
            "GOI",
            "Part II order",
            "CFA will write off loss in consultation with CDA",
            "500",
            "Move Sanctioning authority",
            "Require pre scrutiny by CDA",
            "3",
            "fee is paid out of Consolidated Fund of India",
            "0.5",
            "Free Passage by Air to a place outside India",
            "Units having public Fund Account",
            "six months",
            "Both",
            "Both",
            "Fall clause",
            "All the three",
            "GOI",
            "All the three",
            "2 months",
            "50 lakhs",
            "GOI",
            "Risk & Expenses clause",
            "6 months",
            "12 months",
            "None",
            "Abnormally heavy or unusually low",
            "Either a or b",
            "one year",
            "His Travelling Expenses",
            "All the three",
            "Both",
            "Appropriation",
            "Controlling Officer",
            "Fresh Expenditure",
            "Local Fund",
            "Borrower",
            "a or b",
            "MOD",
            "LAO/PCDA",
            "7",
            "Respective Head of Offices",
            "DGNCC",
            "Army Head Quarters",
            "3 years",
            "GOC in C",
            "Execute a fresh contract",
            "Law Officer",
            "Chief of Personnel",
            "Government Promissory Note",
            "All the three",
            "21 days",
            "Court Attachment",
            "One month",
            "Air Force Form",
            "Local",
            "3",
            "GOI",
            "Service Head Quarters",
            "Defence Procurement Manual",
            "Tender Purchase Committee",
            "Cash",
            "Price Negotiation Committee",
            "Commercial Negotiation Committee",
            "Next higher authority",
            "Request for proposal",
            "Limited Tender Enquiry",
            "Executive",
            "Authority sanctioning the contract",
            "25000",
            "Last Purchase Price",
            "Honorarium",
            "Major",
            "Revenue",
            "None",
            "Open Tender Enquiry",
            "Three weeks",
            "Three",
            "Original Equipment Manufacturer",
            "Buy Back offer",
            "Rate Contract",
            "Ministerial Appointment",
            "MOD",
            "All the three",
            "Compensatory Allowance",
            "Date of signature of officer authorized to issue MRO",
            "Government servants",
            "MES",
            "Loss of public money",
            "Competent Financial Authority",
            "PCDA/CDA",
            "CFA",
            "Authority to make appointment in lower &higher rank",
            "Surrender",
            "Fee",
            "Ministry of Defence",
            "Price",
            "Next higher CFA",
            "six months",
            "Office Contingencies",
            "a year",
            "GOC in c",
            "Miscellaneous Expenditure",
            "Appointed as Arbitrator in case of dispute between Department (other than he is working) and a private party",
            "Non Recurring Charges",
            "1243",
            "MOD",
            "1 year",
            "There shall be retendering",
            "They bear",
            "Gross",
            "3000",
            "PCDA/CDA",
            "Next higher CFA",
            "None",
            "GOI",
            "CFA",
            "Lowest of a, b",
            "Both",
            "CFA in consultation with CDA/IFA",
            "Payee and witnessed by Executive",
            "Indian Supply Mission",
            "War Equipment Tables",
            "Net",
            "Services H.Qrs. through CDA",
            "2 months",
            "CDA, Next higher CFA",
            "None. Fresh Contract is executed with party willing to take up",
            "1/3rd",
            "DGOF",
            "Both b & c",
            "Both a & b",
            "Sumptuary allowance",
            "Audit Officer",
            "PCDA/CDA",
            "Officer actually performing the duties",
            "Both",
            "15th November",
            "MES",
            "Expenditure",
            "Local Authorities",
            "Senior Audit officer of the command",
            "PCDA/CDA",
            "Finance Division of MOD",
            "Charged Expenditure",
            "Claimant",
            "3,4",
            "DAD",
            "Earnest Money Deposit",
            "Defence Services",
            "Technical Evaluation Committee",
            "None",
            "None",
            "E section of Main office of PCDA",
            "Notice inviting Tender",
            "GOI",
            "Lapses to Government",
            "QMG",
            "Imprest",
            "Earnest Money",
            "Modified Appropriation",
            "General Average",
            "No",
            "Check Rolls",
            "Contract",
            "vote on account",
            "Honorarium",
            "42094",
            "Both",
            "Priced Vocabulary Rate",
            "Gross, Net",
            "Executive",
            "Deputy Assistant Director, Electrical and Mechanical Engineering",
            "Charged Expenditure",
            "Liquidated Damages",
            "The unexpended balance of cash assignment lapses and unexpended money in imprest is deposited to government account through M.R.O.",
            "Tender",
            "Book to the accounts of the year in which final decision is taken though at the same all possible efforts should be made to expedite the decision",
            "Both 1 and 2 are wrong",
            "Orders of GOI take effect from the date they bear unless otherwise specified",
            "Assistant Recruiting Officer",
            "CGDA",
            "With prior concurrence of IFA subject to fulfilment of stipulated conditions",
            "Priority Procurement Plan",
            "All the three",
            "All the three",
            "0.1",
            "4,2;3;1",
            "Action taken by CDA is in order",
            "1,3 are correct",
            "He may be asked to assist but will not as a member of such court",
            "Not in order",
            "Not in Order",
            "In order",
            "Only One",
            "Amount shall be treated as written off",
            "All the three",
            "LCH",
            "Electronic Data Processing",
            "Last working day of the month",
            "Para 43 of FR Part II",
            "ETG",
            "Overtime performed beyond 14 consecutive calendar day",
            "Public funds",
            "Both",
            "Field Imprest Payment Instructions",
            "10 days",
            "Received",
            "All",
            "Transferred from one Estt. to another",
            "Warrants for money",
            "Captain",
            "three months",
            "LAO/RAO",
            "Grant of Military Service Pay",
            "Naval pay office",
            "All the three",
            "None",
            "Stock Book Rate as on date of issue",
            "All the three",
            "Deputy Chief of Army Staff",
            "CDA of the PAO with which Imprest Holder is most concerned",
            "Military Secretary Branch",
            "Preceding",
            "Full",
            "Library",
            "6",
            "None",
            "Latest Payment issue rates",
            "Month",
            "surrendered to the authority who initially allotted",
            "Either of a, b",
            "GOC in C",
            "Calendar year",
            "Pay Slip",
            "Both",
            "Official Designation of Imprest Holder",
            "PCDA (O)",
            "Certificate for voucher lost",
            "None",
            "None",
            "monthly",
            "None",
            "First working day of April",
            "IRLA is transferred",
            "Signal works services Grant",
            "day",
            "Indian Medical Service",
            "PCDA/CDA",
            "Sheet Roll",
            "Master General of Ordnance",
            "Ceiling Monetary limit",
            "Scales of Rations and Supplies",
            "Commanding Officer of the unit/Establishment",
            "Public fund",
            "Deputy Chief of Army Staff",
            "GOC in C",
            "Regional CDA",
            "Paid vouchers are retained by Audit Offices",
            "All the three",
            "Regional CDA of Armed Forces Hospital",
            "Retrenchments",
            "Cash",
            "10 days",
            "30th June",
            "audit report of PAO",
            "Name of the payee",
            "3 months",
            "1/3rd",
            "Master General of Ordnance",
            "cannot be acceded to",
            "When a PBOR is transferred to one establishment to another",
            "All the three",
            "All the three",
            "Both",
            "All the three",
            "Government dues",
            "Free",
            "2",
            "10th",
            "Government Solicitor",
            "CGDA",
            "5",
            "Commercial",
            "April",
            "Reserve Guiding Price",
            "Duplicate",
            "Half yearly",
            "5% below market price or face value whichever is less",
            "Nick Name",
            "Both",
            "PCDA/CDA",
            "Dummy DIDS",
            "30",
            "Triplicate",
            "Accounts",
            "GE concerned",
            "M section",
            "None",


            "Station Transport Officer",
            "None",
            "None",
            "None",
            "Stores Contract Section",
            "Advance of TA/DA",
            "IA",
            "Temporary Duty",
            "25th April",
            "Half Yearly",
            "Annually",
            "90 days",
            "All the three",
            "5",
            "Permanent Advance",
            "3 years",
            "2 years",
            "Demand Intimations",
            "Accepted Tender Note",
            "AO/AAO MES",
            "Shares certificates",
            "Cantonment Audit Fees",
            "CRV",
            "45 years",
            "Administration section",
            "Station Head Quarters",
            "IAF CDA -13",
            "PCDA (WC) Chandigarh",
            "Addl. CDA/Jt. CDA",
            "Year",
            "Bengaluru",
            "No such restriction",
            "500",
            "bimonthly on the 11th, last of the following month",
            "All the three",
            "Station H.Qrs.",
            "Stores Audit",
            "April",
            "All the three",
            "GO (AN)",
            "Advance of Pay",
            "Store Audit Section",
            "2",
            "First",
            "O&M",
            "All the three",
            "PFRDA",
            "M",
            "Indemnity",
            "ATG",
            "CDA (Army) Meerut",
            "Emergency Cash Requisition",
            "00/018/65",
            "Monthly Expenditure Return/Report",
            "3 years",
            "LAO",
            "Field Cashiers",
            "Transportation Section",
            "Disbursement",
            "form Destroyed",
            "Miscellaneous",
            "Records",
            "All the three",
            "Stores Audit",
            "Black",
            "1",
            "Internal Audit",
            "Local Audit Completion Report",
            "Defence (Payments)",
            "Last Audit Certificate",
            "None",
            "A person below poverty line",
            "CDA Patna",
            "O&M",
            "sampling",
            "30",
            "three weeks",
            "CDA (Army) Meerut",
            "Stores Contract Section",
            "None",
            "25000",
            "7 days",
            "Important communication from A.H.Qrs.",
            "Half",
            "CPGRAMS",
            "2",
            "Demand Register",
            "All the three",
            "40",
            "None",
            "5",
            "Expenditure Angle Sanction",
            "PCDA/CDA",
            "PCDA/CDA",
            "DCDA/ACDA (AN)",
            "automatically lapsed to government",
            "Cheques cancelled",
            "Pre audited",
            "Engineering",
            "OM II Volume II",
            "Stores Contract",
            "IA",
            "Records",
            "Administration",
            "D.O. letters",
            "CGDA",
            "PCDA/CDA",
            "complaint",
            "Controller of Printing and Stationery, Kolkata",
            "Records section",
            "10 years",
            "75 years",
            "5 years",
            "5 years",
            "10",
            "30",
            "Both",
            "Accounts",
            "O&M Cell",
            "Licence Fee bills",
            "GPF payments to employees",
            "0.05",
            "25000",
            "IA section",
            "Accounts/ORs Section",
            "Miscellaneous",
            "Miscellaneous",
            "Stores Audit",
            "Accounts Section",
            "Administration",
            "Administration Section",
            "Demand Register",
            "PCDA/CDA",
            "One occasion",
            "Office Contingencies",
            "Rs. 50/-",
            "3 years",
            "Monthly",
            "Nil",
            "M section",
            "Casual leave in same station",
            "a year",
            "PCDA (SC) Pune",
            "Post Contractual Monitoring",
            "Indemnity Bond",
            "Outstanding Balance",
            "CDA in whose area the work is carried out",
            "2nd January",
            "Month",
            "None",
            "Miscellaneous section",
            "Death Benefits",
            "Both",
            "Accounts Section",
            "Stores Audit",
            "CMP",
            "5 years",
            "Public Account Department",
            "2",
            "Vetting of CST",
            "Integrated Financial Advice",
            "As decided by PCDA",
            "Miscellaneous section",
            "Stores Audit section",
            "Transportation section",
            "Embarkation Commandant",
            "PCDA (SC) Pune",
            "Store Audit section",
            "Internal Audit",
            "Transportation",
            "IA cell",
            "Disbursement",
            "IA",
            "O&M",
            "IFA cell",
            "2 lakhs",
            "1 year",
            "6 years",
            "Head of the Department",
            "10 years",
            "GOI sanctions/orders",
            "Valuable",
            "Pigeon hole",
            "110 years",
            "All the three",
            "None",
            "37987",
            "Admin",
            "None",
            "Defence Pension",
            "Schedule III",
            "Subscriber’s Contribution File",
            "0.8",
            "Lapse to Government",
            "None",
            "37712",
            "2",
            "CDA",
            "Pay and Allowances",
            "48 Hours",
            "Indemnity Bond",
            "Records Section",
            "Kolkata",
            "9",
            "Director of Military Regulations and Forms",
            "Both",
            "None",
            "10 years",
            "3 months",
            "Home Town",
            "Internal Audit",
            "10 years",
            "All the three",
            "None",
            "15",
            "the department which sanctions the leave",
            "8000",
            "10",
            "30 days",
            "All the three",
            "O&M cell",
            "10 years",
            "5 years",
            "10",
            "IA cell",
            "D section",
            "Controller of Stamps, Nasik",
            "Government Security Printing Press, Nasik",
            "1st June",
            "HRA",
            "35 years",
            "5 years",
            "NPS",
            "MROs",
            "Store Contract Section",
            "England",
            "CCO- 9",
            "Records",
            "Quintuplicate",
            "Administration",
            "Per capita",
            "5 years",
            "4",
            "Miscellaneous Advances",
            "Focal Point Branch",
            "0.4",
            "Date of joining the service",
            "Husband",
            "All the three",
            "Ministry of Finance",
            "Ministry of Finance",
            "CAPEX/OPEX",
            "None",
            "None",
            "25000",
            "25001-2.5 Lakhs",
            "3",
            "Limited Tender Enquiry",
            "More than 3",
            "25 lakhs",
            "DGS&D",
            "Technical",
            "Proprietary Article Certificate",
            "Original Equipment Manufacturer",
            "Government e- Market Place",
            "Mandatory",
            "Ministry of Commerce",
            "25000",
            "Above 25000 upto 5 lakhs",
            "5 lakhs",
            "Both",
            "50",
            "Bill",
            "Voucher",
            "2",
            "Pay and Allowances",
            "Gazetted Officer",
            "1983",
            "5",
            "6",
            "8",
            "12",
            "9",
            "8",
            "14",
            "8",
            "All the three",
            "CGA",
            "CGA",
            "CGA",
            "Claim",
            "Compilation sheet",
            "2",
            "01.04.1990",
            "All the three",
            "Take it as  receipt and write off the loss under appropriate head",
            "Cost Accountant",
            "None",
            "None",
            "Both"
    };

}
