package com.indrajha.sasquiz;

public class Part2QuestionList {
    public static String[] questions = {
            "Every officer taken into the payment of PCDA (O) for the first time will be allotted",
            "All events in service career of an Army Officer affecting his pay and allowances, promotions etc. are notified through",
            "Reimbursement of Children Education Allowance for disabled children of Army officers shall be payable at ",
            "Army Officers availing annual leave ",
            "Army officers serving in operation areas",
            "Furlough is a kind of ",
            "Licence fee bills in respect of Army Officers are sent to ____?",
            "The maximum entitlement of casual leave for army officers in a calendar year is",
            "IRLA stands for",
            "Rate of Dearness Allowance for Army Officers",
            "DSOP fund refers to",
            "An officer shall exercise the option of this pay fixed on promotion",
            "If charge is transferred to an officer in the afternoon, he is deemed to assume charge from",
            "The pay of higher rank to which an officer present on duty is erroneously promoted, will be discontinued from the date",
            "The amount of advance for the purpose of LTC will be limited to _____ % of the estimated amount?",
            "A retired officer in receipt of pension, when reemployed will ",
            "Ration Money claims of Army Officers are passed by ",
            "_____ charts are maintained in PCDA (O) to watch for the monthly receipt of Nominal Rolls?",
            "How many digits/alphabets will you find in the CDA (O) Account Number containing the Account Number properly allotted to Army Officer?",
            "Which of the following cells does not function under Ledger Wing of PCDA (O)?",
            "Which of the following sub sections/cells does not function under Accounts Section of PCDA (O)?",
            "How many groups function under Technical Section of PCDA (O)?",
            "Which of the sections of PCDA (O) maintains ‘Master Note Book’ of all Orders pertaining to officers’ Pay & Allowances including Travelling Allowances?",
            "Replies to the objections raised by Inspection Team of CGDA’s Office, will be monitored by which of the following sections of PCDA (O)?",
            "The selection process for percentage audit will be so devised as to subject each IRLA to percentage audit once in a cycle of __ by PCDA(O)?",
            "Expand SL Officers with reference to work related to PCDA (O)?",
            "Expand RC Officers with reference to work related to PCDA (O)? i.e. ___ officers",
            "What is the prescribed time limit for submission of the medical claims after completion of treatment?",
            "A second or subsequent advance for the purchase of Personal Computer cannot be granted before the expiry of ____ years from the date of drawal of earlier advance? ",
            "Family pension is admissible to the family of deceased employee @ ____% of Last Pay drawn by the government servant?",
            "CDA (O) Account Number contains ____  how many digits in addition of one alphabet?",
            "From which of the following records, it is ensured by PCDA (O) that no officer is paid by more than one Ledger Wing?",
            "Lump sum advances drawn by Field Imprest Holders from Field Cashiers will be intimated by PCDA (O) to ____?",
            "Which of the following documents is not relevant for opening of IRLA of newly commissioned Army Officer by PCDA (O)?",
            "Authorization slips are issued by which of the following sections of PCDA (O)?",
            "Which of the following absence is not a type of leave but treated as duty in the case of Commissioned Officer?",
            "Separation allowance is not payable though the Army officer is married but not attained the age of ___?",
            "Which section of PCDA (O) has to give confirmation of a vacancy of Officer to PAO for admitting Acting Allowance to JCO in his place?",
            "Maximum period of absence permitted as sick list concession in respect of Army Officers is ____?",
            "Which of the following actions by PCDA (O) is not true in the case of Funds paid by Field Cashier to Field Imprest Holders?",
            "IRLA of Army Officer is not maintained by PCDA (O) in which of the following cases of Officers proceeding on _______?",
            "Which of the following appointments are known as Tenure appointments in respect of Army Officers?",
            "Newly commissioned officer shall not be entitled to pay on first appointment for a period in excess of ___ days before the date on which he reports for duty?",
            "Purchase of Motor car should be made within ___ of the date on which the advance is drawn by Army Officer?",
            "Which of the following allowance is admissible along with Siachen Allowance?",
            "Which of the following sections is found in PAO (ORs) but not found in PCDA (O)?",
            "Which of the following statements is not correct w.r.to Furlough leave of Army Officers? ",
            "When reduction to lower stage of pay is awarded under VI CPC structure as punishment, Pay will be reduced in which of the following manners?",
            "Which of the following records is maintained by PCDA (O) reflecting task wise, corps wise and unit wise list of Army Officers to ensure only IRLA is maintained for each officer?",
            "Annual leave for army officer is not granted in continuation of _____?",
            "Armed Forces List Cell functions under which section/wing of PCDA (O)?",
            "An Army Officer retiring in January of a year can accumulate ____ days of un availed Annual Leave of the year of retirement for Leave Encashment purpose? ",
            "Siachen allowance is not admissible to Army Officer concurrently with which of the following allowances?",
            "In the case of hospitalization of Army Officer, ______ pay and allowances are admissible to him/her for such period?",
            "SCCIA is concurrently admissible along with which of the following allowances?",
            "In the case of Recall from leave in respect of Army Officer, travel time from leave station to duty station will be treated as ___?",
            "Officers of the rank of ____ and above have the option of drawing TPTL or to use Government transport?",
            "LPC cum data sheet of retiring Army Officer is prepared in ____ by PCDA (O)?",
            "The month-wise LPC-Cum-Data Sheets, centrally maintained by the Pension Cell of PCDA (O) will be retained for __, commencing from the month of Retirement of the officer? ",
            "A single window system for passing all advance payments of TA/DA, LTC etc. has been established in PCDA (O). Name the section?",
            "Where Pet animals are conveyed as part of baggage by Army officers, the charges are restricted by PCDA (O) to within the maximum entitlement for conveyance of baggage by __? ",
            "Which section of PCDA (O) is responsible to render quarterly report on financial irregularities?",
            "Non-Effective Account Files received in the Section initially will be treated as ___by permanent records section of PCDA (O) for one year?",
            "Which of the following sections is not a section/wing of PCDA (O)?",
            "Advance of pay to Army Officers paid by Field Cashier is compiled to ____ suspense head (till recovered in IRLA)?",
            "Transactions uploaded by PCDA (O) under SBI CMP system, but rejected are classified as ______?",
            "Which of the following documents is not required to open a IRLA in PCDA (O) in respect of Officer granted commission in Army?",
            "Certificate audit is conducted by ______ in PCDA (O) office?",
            "Which of the following sections in PCDA (O) is not functioning under Administration Section?",
            "Lump sum advances paid to Field Imprest Holders by Field Cashiers are compiled to _____ suspense head",
            "CDA (O) Account Number allotted to each Army Officer is made up of ____ components?",
            "Date of Birth, Home Town and previous service particulars etc. in respect of Army Officer are received in PCDA (O) through ___ document?",
            "All Hospitalization cases will be monitored through ________Register in PCDA (O) office?",
            "Who is responsible for safe custody of LPC seal and Payment Authority Seal in PCDA (O) office?",
            "A cheque with more than _______ alteration/alterations should not be issued by D section of PCDA (O)?",
            "First component of CDA (O) Account Number represents ____?",
            "Which of the following actions will be taken simultaneously at the time of opening of new IRLA in respect of Army Officer?",
            "Casualties occurring in operational areas are known as _____?",
            "Part II orders of Army Officers are received in ___ section/wing /cell of PCDA (O)?",
            "Total of all DP sheets as per Control Register would be agreed with total of the relevant ______ by D section of PCDA (O)?",
            "Second component of CDA (O) Account Number represents _____?",
            "___________ is a documentary medium through which entitlement of Pay is intimated to EDP Centre?",
            "Expand POW?",
            "Monthly report of Central Index, maintained by EDP centre of PCDA (O)  is handed over to ____ section/wing/cell?",
            "Which of the following sections of PCDA (O) is entrusted with the duty of scrutiny and vetting of Draft Gazette Notifications?",
            "Third component of CDA (O) Account Number represents ____?",
            "DO II inputs are given by Ledger wings for intimating changes in pay and allowances, promotions etc. through _______?",
            "Pay accounts of Officers serving in Indian Embassies abroad other than UK are maintained by PCDA (O) ______?",
            "When you find a flag “S” against details of one Army Officer in Central Index, what do you understand about the status of his account? ",
            "_ section of PCDA (O) is responsible to deal with Court, AFT & RTI cases on pay & allowances entitlements of serving and released officers?",
            "First component of CDA (O) Account Number is represented by _____?",
            "Which of the following EOL granted automatically count as qualifying service for pension and increments without any further sanctions?",
            "Qualification pay claims and Technical Allowances claims fall the under the category of ______ claims?",
            "Dealing with Test Audit Objections regarding Pay and Allowances of officers is one of the functions of ___ of PCDA (O)?",
            "Second component of CDA (O) Account Number is represented by _____?",
            "Pamphlet of “Documentation Procedure for Publication of Part II Orders (Officers)” is issued by _____ Integrated H.Qrs. of MOD (Army)?",
            "Qualification Grant is not admissible to ______officers?",
            "Ledger Wing to eliminate the possibility of opening a duplicate IRLA requests R section through a forwarding memo marked as for “____”?",
            "Individual Running Ledger Account of Officers are closed to a ____ balance at the end of every month by PCDA (O) Pune?",
            "Third component of CDA (O) Account Number is represented by _____?",
            "Missing Part II Orders will be called for by EDP Centre, giving suitable messages on ________________?",
            "Initial claim for reimbursement of house rent in respect of an army officer is pre scrutinized by ______?",
            "Which of the following cells/sub sections work under Accounts Section of PCDA (O)?",
            "Contribution to DSOP fund will be commenced in the IRLA of Army Officer on completion of ____ from the date of Commission?",
            "Which of the following components of CDA (O) Account Number remains unchanged?",
            "Actioned Part II Orders after due post audit will be filed in ________, which may be referred to for future linking etc",
            "Details of leave availed by army officer is available in the ______ of Entitlement IRLA?",
            "Expand FTCR?",
            "Contribution to the DSOP fund is recovered by computerized system in respect of Army Officer @ ___ as minimum contribution?",
            "CDA (O) Account Number is represented by ____ (digits + Alphabets) together in all?",
            "New Pension Scheme is applicable to which of the following officers joining service on or after 01.01.2004?",
            "Details of Bank Account of Army officer is available in _____ of Entitlement IRLA",
            "Which of the following is not the function of PCDA (Officers) Pune? ",
            ". Part II orders published in respect of Army Officers are broadly divided into ____ categories in PCDA (O)?",
            "Study Allowance is payable for a period not exceeding _____?",
            "If an appointment is tenable in alternate ranks, _________ can be held appointed to such post?",
            "Payments of refunds of cash receipts and recoveries cannot be made without the approval of ____?",
            "Which of the following is not a section/wing/cell/sub section of PCDA (O) Pune?",
            "When you find a flag “D” against details of one Army Officer in Central Index, what do you understand about the status of his account?",
            "The Register in which permanent list of IRLAs transferred out by a Ledger wing is maintained is known as ____?",
            "For the purpose of Scale Audit, ____ month’s strength returns of Officers in each half year are selected by Wing Officer?",
            "Central Index of Army Officers is maintained by which of the following sections/groups/wings/sub sections of PCDA (O) Pune?",
            "The responsibility for verifying the competence of Station Commander for according sanction to hire private accommodation rests with?",
            "At any point of time the difference between the last serial numbers of 'A' list Register and 'B' list Register of LW will give __ (information)?",
            "Officers on Course of Instructions of 10 weeks or more duration are shown separately as officers _______ in Strength Returns by units?",
            "Pension/Leave salary sub section of PCDA (O) is responsible for recovery of pension/leave salary contribution in case of ______?",
            "Sanction for hiring of private accommodation by Army Officer is initially accorded by the Station Commander only for a period of ___?",
            "Army Group Insurance scheme has been introduced w.e.f. ______?",
            "Officers sick in hospital or on sick leave are continued to be shown in the Strength Return in the proper place with a suitable remark.",
            "Details of Interest bearing advances are available in which portion of Entitlement IRLA maintained in the office of PCDA (O) Pune?",
            "Rental ceilings for hiring of accommodation for separated families of service officers will be of ____ their class of entitlement?",
            "Army Officers Benevolent fund is not recoverable from which of the following categories of Officers?",
            "Officers of a Unit attached on disciplinary grounds to another unit or suspended from duty and attached are continued to be shown in the Strength Return against the appropriate appointment",
            "Details of promotions, allowances and awards in respect of Army officer are available in which portion of Entitlement IRLA?",
            "Monthly Test check of IRLAs is done by AO/SAO to the extent of ______? ",
            "Which of the following statements is true with reference to excess strength of officers posted in units is noticed during scale audit?",
            "Details of Hostel subsidy and Children Education Allowance in respect of Army Officer are available in which portion of Entitlement IRLA?",
            "Advance of Pay is admissible to Army Officers in which of the following circumstances? ",
            "Which of the following withdrawals/advances is not permitted from DSOP fund in respect of Army Officers?",
            "Which of the following classes of Punching Medium voucher is not operated by PCDA (O) Pune?",
            "CDA (O) Account Number allotted to an officer consists of ____ digits and ____ Alphabets?",
            "Issue regarding counting of pre-Commissioned Service is decided by the Administrative Authority, in consultation with _____?",
            "__section/wing/cell of PCDA (O) deals with Recovery of LF and allied charges of Army Officers in occupation of Govt. Accommodation? ",
            "Census of IRLAs is conducted by Ledger Wing of PCDA (O) once in ____?",
            "__section/wing/cell of PCDA (O) deals with Scale audit of strength returns of Army Officers posted in various units?",
            "Which section/wing/sub section/cell of PCDA (O) deals with allotment of new CDA Account Number to Army Officer?",
            "In case of combined leave, the Leave Advance is admitted only for ____ portion in respect of Army Officers?",
            "DSOP Fund account of Army Officer seconded to Air Force is maintained by _____?",
            "At the time of opening a new IRLA, SS Coordination group obtains a certificate from R section duly marked as “_________”?",
            "In how many instalments (maximum) principal amount of House Building Advance is to repaid by Government Servant?",
            "Which of the following is not true with reference to officer reported as Prisoner of war?",
            "What is the prescribed percentage for conducting scale audit of Strength returns of Army Officers in PCDA (O)?",
            "Arrears of license fee and allied charges bills due to delay in receipt in the office of PCDA (O) are recoverable in __________?",
            "Armed Forces List Cell functions in which of the following offices?",
            "Flying Allowance is admissible concurrently with which of the following Allowances in respect of Army Officers?",
            "Army officers can accumulate up to a maximum of ___ days of Annual Leave in a calendar year for the purpose of encashment?",
            "Authorization Slips are generated by the system for ____ Part II orders?",
            "__ of the amount of Flying Allowance will be credited to DSOP Fund in addition to the contribution the officer is already making to the fund?",
            "Which of the following is not a purpose for which Central Index is maintained in PCDA (O)?",
            "Validation reports generated by EDP in respect of Part II orders will be checked __% by the respective AAOs with the Part II Orders?",
            "EDP Centre generates a list of officers retiring ____ prior to the Retirement and hand over to Final Settlement Review Group for necessary action in PCDA (O) Pune? ",
            "Officiating Promotion may be granted in case when an officer officiates in an appointment in the higher rank for a minimum period of ___?",
            "Monthly PLI Schedules are forwarded by PCDA (O) to ________?",
            "The casualty of forfeiture of service is recorded in the IRLA in ____ink in the office of PCDA (O) Pune?",
            "Officers of a unit attached on disciplinary grounds to another unit or suspended from duty and attached are continued to be shown in the Strength Return (Nominal Roll) against the appropriate appointment. ",
            "Promotion In-situ shall be resorted to for a maximum period of __, within which the officer promoted will be posted to a suitable appointment? ",
            "Highly Active Field Area Allowance is not admissible to the officers working in which of the following units?",
            "Entitlements admissible in the case of Battle Casualties are governed by ______ Orders?",
            "The work related to vetting of Draft Gazette Notification (DGN) in respect of Army Officers was transferred to PCDA (O) w.e.f. ___?",
            "In the case of transfer of Army Officer from one unit to another, handing/taking over period of __ days is allowed for non-stock holding units?",
            "CMFAA is not admissible to army officer if he is on CL for more than _____  days?",
            "Which of the following cases is included in ‘IRLA not generated’ Report in PCDA (O)?",
            "Which of the following claims are of non recurring nature and are not passed through Audit cage of IRLAs of Army Officers?",
            "Who is the competent authority to approve officiating promotion up to the rank of Major?",
            "HAUCA is an allowance granted to Army Officers based on ______ of the location after fulfilling the prescribed conditions?",
            "Which of the following allowances is admissible concurrently with SCCIA in respect of Army Officers?",
            "Office Automation module used in PCDA (O) is named as “Project ______”?",
            "Safe custody of documents like title deed, Mortgage deed and surety bond etc. of Army officers who are granted HBA is the duty of __?",
            "Which section of PCDA (O) is responsible to furnish its comments on ‘Notes for Orders’ on doubtful cases, put up by Wings for ruling?",
            "In the case of Temporary Duty/attachment to a unit in non qualifying area, HAUCA is admissible if the duration exceeds ___?",
            "Expand CHCA? ",
            "IAF CDA -13 (Small) is used for which of the following payments in PCDA (O) Pune?",
            "Advances drawn on Field Cheques by Army officers from Field cashier are recovered in ________ in IRLAs of the officers?",
            "Who is the competent authority to approve officiating promotions in Supersession cases?",
            "IAF CDA -13 (Large) is used for which of the following payments in PCDA (O) Pune?",
            "Quarterly E-TDS returns are filed by _______ section of PCDA (O) for compilation of Tax Deducted at Source in respect of Army Officers?",
            "Expand AWHO? ",
            "Island Special (Duty) Allowance is admissible concurrently with which of the following allowances?",
            "IAF CDA -13 (Large) (Red) is used for which of the following DSOP fund Final Settlement payments in PCDA (O) Pune?",
            "Financing of premiums up to _____ Life Insurance Policies is allowed from DSOP Fund in respect of each officer?",
            "Who is the competent authority to approve officiating promotion to the rank of Lt. Col. (More than six months)?",
            "Siachen Allowance is admissible to officer serving in Siachen Glacier under operation ____?",
            "Which of the following allowances is not admissible concurrently with Para Allowance?",
            "New Account will not be opened by PCDA (O) in the absence of which of the following details of newly commissioned officers?",
            "Accounts of Officers finalized on account of Discharge, Retirement and Superannuation etc. are held in Ledger wing for ___ period and then transferred to Permanent Record section?",
            "Expand DGN?",
            "In the case of transfer of Army Officer from one unit to another, handing/taking over period of __ days is allowed for stock holding units? ",
            "__ is the documentary medium through which Ledger Section intimates EDP Centre, the entitlements of Pay and Allowances of officers fixed/revised periodically by them? ",
            "Accounts of Officers finalized on account of Discharge, Retirement and Superannuation etc. transferred to Permanent Record section are held as _____ Records by Permanent Record Section? ",
            "Who is the competent authority to approve officiating promotion to the rank of Colonel and above?",
            "Pension cell is a sub section of ______ in PCDA (O) Pune",
            "Transportation wing of PCDA (O) does not deal with Travelling Allowance claims of which of the following officers?",
            "_____ acts as the nodal agency for consolidating Pension documents of Army Officers?",
            "Which of the following is not a duty of T wing of PCDA (O) Pune? ",
            ". LPC-Cum-Data-Sheets & amendments, if any, there to in respect of Army Officers are signed only by the ___ nominated for this purpose?",
            "No advance of DA for Temporary Duty in respect of Army Officers beyond ______is paid by PCDA (O)?",
            "Which of the following can be found in the details supplied by EDP Centre to Pension Cell to complete the LPC-cum-Data Sheet in FS cases? ",
            "Officers on TD/Permanent Posting/LTC can draw advance for self or family members, before ____ of proposed date of onward journey?",
            "Expand FPCSC?",
            "When advance is drawn for TA/DA much before journey date, officer should produce the Railway Ticket(s) within __ of the drawal of advance to Controlling Officer?",
            "LPC cum Data Sheet in respect of Army Officers at the time of their retirement is prepared in ____ by PCDA (O)?",
            "Move of an officer to outstation for attachment on __ will not be classified as “Permanent” even if the duration of stay exceeds180 days?",
            "Original LPC cum Data Sheet is sent to PCDA (P) by PCDA (O) ___ in advance of retirement of Army Officers?",
            "No move of an officer shall be classified as ‘Permanent’ if it is undertaken in pursuance of ________?",
            "Copy of LPC cum data sheet need not be sent by Pension Cell of PCDA (O) to which of the following in the retirement case of Army Officer?",
            "Army officer should not use more than ___ one way journey Form D in a calendar year?",
            "In the case of upward revision of Pay after issue of LPC to PCDA (P), amendments of intimation memo are scrutinized and vetted by __?",
            "Where journey is performed by rail without using Form D due to non availability of Form D in Unit / Establishment, reimbursement should be claimed from __ by Army Officer?",
            "Month-wise LPC-Cum-Data Sheets, maintained by Pension Cell will be retained for __ from the month of Retirement of Army officer?",
            "Audit and Demand Register is reviewed once in ___ by the T section of PCDA (O)?",
            "An Army Officer will be entitled to full pay and allowances?",
            "Which of the following is not a responsibility of PCDA (O)? ",
            "An army officer is not eligible for qualification pay in respect of ___?",
            "Which of the following section will not be found in PCDA (O)?",
            "An officer (permanent incumbent) in receipt of parachute pay is placed under suspension. The duties have been attended to temporarily by another officer. In these circumstances ",
            "Which of the following is true, when an army officer avails study leave and draws study allowance?",
            "An army officer cannot be granted Annual leave in combination with",
            "Army officers are entitled to Specialist Pay. Who among the following cannot be treated as a specialist?",
            "An officer granted special outfit allowance leaves his qualifying appointment within one year. He has to refund",
            "Which of the following cannot be classified as a permanent move for an army officer ",
            "Expand A.O.B. fund",
            "Pick out the correct statement out of the following  ",
            "The Pay and allowances of the officers will be ceased ",
            "What is the prescribed % of entitlements Audit in respect of Army Officers",
            "____________is a documentary medium through which entitlement of Pay is intimated to EDP Centre?",
            "Which of the following allowances is not admissible in respect of officer declared Prisoner of War?",
            "___ Branch of Integrated Head Quarters of MOD (Army) is the Head of the Department for the purpose of Grant of HBA to Army Officers?",
            "Appointments of COAS/Lt Generals of AFMS and DGAFMS are _____Appointments?",
            "When an officer fall sick while on duty and is retained on the sick list for a period of 30 days or less, such absence from duty is treated as? ",
            "Technical Section of PCDA (O) conducts Percentage audit of ____ IRLAs in a Quarter?",
            "Central Index is not maintained ___ wise",
            "Which section of PCDA (O) issues cheque books to Field Cashiers?",
            "__ section of PCDA (O) is responsible for Rendition of Expenditure Reports in r/o Army Officers deputed to Assam Rifles, NSG, AWHO etc?",
            "__ is the documentary medium through which each Ledger Section intimates EDP Centre, the entitlements of Pay and Allowances of officers fixed/revised periodically by them? ",
            "For Territorial Army offices Increment is granted on completion of _____  of embodied service?",
            "When Furlough leave is combined with Annual Leave, which is taken first _____?",
            "Cash Assignment Register maintained by Field Cashier Sub Section of PCDA (O) is closed on ____basis?",
            "Discrepancies noticed in the Daily Cash Account submitted by Field Cashier will be reported by PCDA (O) to ____ for investigation?",
            "Which section/wing/sub section/cell is responsible to take action on “IRLA Not Generated Report”?",
            "Inspection of various sections of the office of PCDA (O) is conducted by ____ once in ___?",
            "In the case of Debit balance in respect of Army Officer, Provident Fund monthly contribution will be restricted to ___% of pay?",
            "If the maximum period of Casual Leave availed of by an officer in a calendar year (including extensions mentioned above) is in excess of the leave admissible, the entire spell of Casual Leave (including the period of extension) will be treated as ____? ",
            "What is the retention period of Authorization slips in PCDA (O) office from the month of issue ______?",
            "What is the prescribed % of entitlements Audit in respect of Army Officers"
    };
}
